.section .rodata
        ._a: ".-"
        ._b: "-..."
        ._c: "-.-."
        ._d: "-.."
        ._e: "."
        ._f: "..-."
        ._g: "--."
        ._h: "...."
        ._i: ".."
        ._j: ".---"
        ._k: "-.-"
        ._l: ".-.."
        ._m: "--"
        ._n: "-."
        ._o: "---"
        ._p: ".--."
        ._q: "--.-"
        ._r: ".-."
        ._s: "..."
        ._t: "-"
        ._u: "..-"
        ._v: "...-"
        ._w: ".--"
        ._x: "-..-"
        ._y: "-.--"
        ._z: "--.."
        ._0: "-----"
        ._1: ".----"
        ._2: "..---"
        ._3: "...--"
        ._4: "....-"
        ._5: "....."
        ._6: "-...."
        ._7: "--..."
        ._8: "---.."
        ._9: "----."

        .globl Code
                .quad ._a
                .quad ._b
                .quad ._c
                .quad ._d
                .quad ._e
                .quad ._f
                .quad ._g
                .quad ._h
                .quad ._i
                .quad ._j
                .quad ._k
                .quad ._l
                .quad ._m
                .quad ._n
                .quad ._o
                .quad ._p
                .quad ._q
                .quad ._r
                .quad ._s
                .quad ._t
                .quad ._u
                .quad ._v
                .quad ._w
                .quad ._x
                .quad ._y
                .quad ._z
                .quad ._0
                .quad ._1
                .quad ._2
                .quad ._3
                .quad ._4
                .quad ._5
                .quad ._6
                .quad ._7
                .quad ._8
                .quad ._9
        